### PR TITLE
fix(avatar): add call and on-device presence types

### PR DESCRIPTION
**Pull request by jor-row**
# Description

This PR adds the presence types 'Call' and 'onDevice' to the component 'Avatar'.

# Links

https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-356973

Call: https://www.figma.com/file/NaNrfXjygZtRgMfHAFHjsp/Components---Windows?node-id=4594%3A9499

onDevice: https://www.figma.com/file/NaNrfXjygZtRgMfHAFHjsp/Components---Windows?node-id=4594%3A9149

Screenshot 2022-09-21 at 15 18 26

### CODE REVIEW

**Review by maxinteger — CHANGES_REQUESTED** [review]
The PR looks great, but please add the new presence types to the "Presence Types" and "Common" stories in the storybook

**Comment by jor-row** [comment]
> The PR looks great, but please add the new presence types to the "Presence Types" and "Common" stories in the storybook

@maxinteger 

The screenshot above was taken in storybook and both call and onDevice are showing in storybook when I run ```yarn start```. The story is generated by mapping through all presence types so I didn't need to change anything.

**Comment by jor-row** [comment]
@torgeadelin 
I've added on-mobile and on-hold as presence types 

Screenshot 2022-09-21 at 17 45 49

**Comment by jor-row** [comment]
Also added busy presence type

Screenshot 2022-09-22 at 12 14 37

**Review by maxinteger — APPROVED** [review]

**Review by torgeadelin — APPROVED** [review]
looks gucci!

**Pull request merged**
