### PR TITLE
fix(deps): upgrade react-focus-lock

### PR DESCRIPTION
**Pull request by chrisadubois**
# IMPORTANT

**Currently, this project is closed to any external contributions. Any pull request made against this project from external sources will likely be closed. If you would like to make changes to this project, please fork this project.**

# Guide

**This "Help" section can be deleted before submitting this pull request.**

*Update the name of this pull request to reflect the following shape:*

```
{type}/{scope?}/{message}
```

* **type** - A [conventional commit type](https://github.com/conventional-changelog/commitlint/tree/master/%40commitlint/config-conventional#type-enum) **REQUIRED**
* **scope** - The kabab-case scope of the changes in this request
* **message** - A short, kebab-case statement describing the changes **REQUIRED**

*Provide a general summary of the scope of the changes in this pull request.*

* [Readme](https://github.com/momentum-design/momentum-react-v2/blob/master/README.md)
* [Getting Started Guide](https://github.com/momentum-design/momentum-react-v2/blob/master/GETTING_STARTED.md)
* [Contributing Guide](https://github.com/momentum-design/momentum-react-v2/blob/master/CONTRIBUTING.md)

# Description

upgrade react-focus-lock, which has added a number of accessibility fixes since the version which was previously here, such as the requirement for non positive tab indices

# Links

https://github.com/theKashey/react-focus-lock/pull/182

### CODE REVIEW

**Comment by chrisadubois** [comment]
i did test it out on storybook, locally and didn't see any issues as well, though it is used in a legacy component with pretty crazy stories

**Review by chburket — APPROVED** [review]
lgtm

**Comment by chrisadubois** [comment]
I also checked the changelog and am not seeing any breaking changes listed there, just backwards compatible bug fixes. PLus we need this in order to fix accessibility issues

**Comment by chrisadubois** [comment]
https://github.com/theKashey/react-focus-lock/blob/master/CHANGELOG.md

**Comment by chrisadubois** [comment]
it does not overlap with react-aria either

**Comment by chrisadubois** [comment]
Screenshot 2024-09-03 at 2 35 42 PM
Screenshot 2024-09-03 at 2 35 37 PM

**Pull request merged**
