### PR TITLE
fix(space-row-content): fix text spacing issue of space row content component

### PR DESCRIPTION
**Pull request by weiwli2**
# IMPORTANT

**Currently, this project is closed to any external contributions. Any pull request made against this project from external sources will likely be closed. If you would like to make changes to this project, please fork this project.**

# Guide

**This "Help" section can be deleted before submitting this pull request.**

*Update the name of this pull request to reflect the following shape:*

```
{type}/{scope?}/{message}
```

* **type** - A [conventional commit type](https://github.com/conventional-changelog/commitlint/tree/master/%40commitlint/config-conventional#type-enum) **REQUIRED**
* **scope** - The kabab-case scope of the changes in this request
* **message** - A short, kebab-case statement describing the changes **REQUIRED**

*Provide a general summary of the scope of the changes in this pull request.*

* [Readme](https://github.com/momentum-design/momentum-react-v2/blob/master/README.md)
* [Getting Started Guide](https://github.com/momentum-design/momentum-react-v2/blob/master/GETTING_STARTED.md)
* [Contributing Guide](https://github.com/momentum-design/momentum-react-v2/blob/master/CONTRIBUTING.md)

# Description

*The full description of the changes made in this request.*
fix text spacing issue of space row content component, by add tagName="div" attribute to <Text>

# Links

*Links to relevent resources.*
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-506036

### CODE REVIEW

**Comment by gabrielchl** [comment]
|before|after
|-|-|
|Screenshot 2024-10-17 at 10 24 06|Screenshot 2024-10-17 at 10 24 07|

it seems to have gotten rid of the bold text + made the text wrap

**Comment by weiwli2** [comment]
> before	after
> storybook	Screenshot 2024-10-17 at 10 24 06	Screenshot 2024-10-17 at 10 24 07
> app	Screenshot 2024-10-17 at 10 38 23	text spacing increased: Screenshot 2024-10-17 at 10 38 30
> it seems to have gotten rid of the bold text + removed the text-overflow ellipsis style

Thanks for reminding me, I missed these two cases, I will fix them

**Review by JudyZhuHz — APPROVED** [review]

**Comment by JudyZhuHz** [comment]
image

**Comment by gabrielchl** [comment]
hi, it looks like now the 2nd line also becomes bold when the first line is

before:
Screenshot 2024-10-18 at 10 13 30

after:
Screenshot 2024-10-18 at 10 13 32

**Pull request merged**
