### PR TITLE
chore(tooling): update node and typescript

### PR DESCRIPTION
**Pull request by maxinteger**
# Description

- updates nodejs to the next lts version, 22
- updated TS to the make it compatible with @types/node@22

### CODE REVIEW

**Review by cscheffauer — COMMENTED** [review]
Just a comment (haven't reviewed the changes):
Can we make sure this thread is addressed?
https://stackoverflow.com/a/70020984
Like the "moduleResolution" is set correctly?
thanks!

**Comment by maxinteger** [comment]
Please note,

- when you test this PR you need to remove the `node_modules` and install everything again
- if you see `Error: error:0308010C:digital envelope routines::unsupported` then you have to add the `NODE_OPTIONS=--openssl-legacy-provider` before run yarn, eg: `NODE_OPTIONS=--openssl-legacy-provider yarn start`

**Comment by maxinteger** [comment]
> Just a comment (haven't reviewed the changes): Can we make sure this thread is addressed? https://stackoverflow.com/a/70020984 Like the "moduleResolution" is set correctly? thanks!

Thanks for the tip

I updated the `moduleResolution` to `node16`, but I did not changed the exports in the package.json. That will be another PR

**Comment by chrisadubois** [comment]
did you test this with the webclient? else lgtm

**Review by cscheffauer — APPROVED** [review]

**Pull request merged**
