### PR TITLE
fix(Icon): new momentum-design icons

### PR DESCRIPTION
**Pull request by shivani1211**
# IMPORTANT

**Currently, this project is closed to any external contributions. Any pull request made against this project from external sources will likely be closed. If you would like to make changes to this project, please fork this project.**

# Guide

**This "Help" section can be deleted before submitting this pull request.**

*Update the name of this pull request to reflect the following shape:*

```
{type}/{scope?}/{message}
```

* **type** - A [conventional commit type](https://github.com/conventional-changelog/commitlint/tree/master/%40commitlint/config-conventional#type-enum) **REQUIRED**
* **scope** - The kabab-case scope of the changes in this request
* **message** - A short, kebab-case statement describing the changes **REQUIRED**

*Provide a general summary of the scope of the changes in this pull request.*

* [Readme](https://github.com/momentum-design/momentum-react-v2/blob/master/README.md)
* [Getting Started Guide](https://github.com/momentum-design/momentum-react-v2/blob/master/GETTING_STARTED.md)
* [Contributing Guide](https://github.com/momentum-design/momentum-react-v2/blob/master/CONTRIBUTING.md)

# Description

Fixed the active state of in-meeting raise-hand icon.

Before:
image-2023-01-05-13-12-31-530

After:
Screenshot 2023-02-24 at 3 15 16 PM

# Links

*Links to relevent resources.*

JIRA: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-394442

### CODE REVIEW

**Comment by shivani1211** [comment]
using yarn berry

**Comment by torgeadelin** [comment]
looks good but have some questions:
- we already had a PR from Christoph with similar chages, why the new PR?
- why yarn berry?

**Review by InteractiveTimmy — APPROVED** [review]
LGTM!

This looks like a replacement for this [stale pull request](https://github.com/momentum-design/momentum-react-v2/pull/343) that never got merged.

Please respond to the comments from @torgeadelin prior to merging this pull request.

**Comment by shivani1211** [comment]
@torgeadelin,

- It is a stale PR, we can merge either this or that, doesn't matter i guess. This PR will prolly not have any merge conflicts etc since it is on latest code.

- Used Yarn berry since it is the latest version, is there an issue with yarn berry?

- Yes I have tested this locally, the above screenshots are from local.

**Comment by shivani1211** [comment]
> looks good but have some questions:
> 
> * we already had a PR from Christoph with similar changes, why the new PR?
> * why yarn berry?
> * have you tested by locally linking the package in Cantina

@torgeadelin,

It is a stale PR, we can merge either this or that, doesn't matter i guess. This PR will prolly not have any merge conflicts etc since it is on latest code.

Used Yarn berry since it is the latest version, is there an issue with yarn berry?

Yes I have tested this locally, the above screenshots are from local.

**Review by torgeadelin — APPROVED** [review]

**Pull request merged**
